name: build and push nuget package
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project and create NuGet package
        run: dotnet pack --configuration Release -p:PackageVersion=1.0.${{ github.run_number }} --output nupkg
        
      - name: Push NuGet package to server
        run: dotnet nuget push nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
